version: "3.8"

services:
  db:
    container_name: postgres-local
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=db
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  web:
    build: .
    env_file:
      - .env
    ports:
      - "3100:3100"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: nodemon -L --watch src --exec yarn dev
    depends_on:
      - db
volumes:
  postgres-db:
  pgadmin-data:
